import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            <meta name="description" content="Plataforma Estimular Digital"/>
            <meta name="author" content="Estimular Digital"/>
            <title>Estimular Digital</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className="header-area header-sticky">
          <div className="container">
            <div className="row">
              <div className="col-12">
                <nav className="main-nav">
                  <a href="#" className="logo">
                  <img src={'../styles/assets/images/logo-ed.png'} height="80px" alt="Estimular Digital"/> | Home
                  </a>
                  <ul className="nav">
                    <li className="scroll-to-section"><a href="#top" className="active"><i className="ti-home"></i>Home</a></li>
                    <li><a href="cursos.js"><i className='ti-user'></i> Tutoria</a></li>
                    <li className="scroll-to-section"><a href="#courses"><i className='ti-book'></i> Cursos</a></li>
                    <li className="scroll-to-section"><a href="#apply"><i className='ti-pencil-alt'></i>Matrícula</a></li>
                    <li className="scroll-to-section"><a href="#contact"><i className='ti-mobile'></i>Contato</a></li>
                  </ul>
                  <a className='menu-trigger'>
                  <span>Menu</span>
                  </a>
                </nav>
              </div>
            </div>
          </div>
        </header>

        <div className={styles.grid}>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
