export default function principal()
{
    return (
        <div className={styles.container}>
        <Head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            <meta name="description" content=""/>
            <meta name="author" content="Estimular Digital"/>
            <title>Estimular Digital</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="../styles/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
            <link rel="stylesheet" type="text/css" href="../styles/assets/icon/themify-icons/themify-icons.css"/>
            <link rel="stylesheet" href="../styles/assets/css/fontawesome.css"/>
            <link rel="stylesheet" href="../styles/assets/css/templatemo-edu-meeting.css"/>
            <link rel="stylesheet" href="../styles/assets/css/owl.css"/>
            <link rel="stylesheet" href="../styles/assets/css/lightbox.css"></link>        
        </Head>
  
        <main className={styles.main}>
           
        </main>
  
        <footer className={styles.footer}>
          
        </footer>
      </div>        
    )
}